export const ROLES = {
  USER: 'USER',
  ADMIN: 'ADMIN',
  SUB_ADMIN: 'SUB_ADMIN'
};

export const LISTING_MODERATOR_ROLES = [ROLES.ADMIN, ROLES.SUB_ADMIN];

export const ASSIGNABLE_USER_ROLES = [ROLES.USER, ROLES.ADMIN, ROLES.SUB_ADMIN];

export const SUB_ADMIN_MODERATABLE_STATUSES = ['APPROVED', 'SUSPENDED'];
