// Complete location data structure for seeding
export const locationsData = {
  'Canada': {
    'Alberta': ['Airdrie', 'Athabasca', 'Banff', 'Barrhead', 'Bassano', 'Beaumont', 'Beaverlodge', 'Black Diamond', 'Blackfalds', 'Bon Accord', 'Bonnyville', 'Bow Island', 'Brooks', 'Calgary', 'Calmar', 'Camrose', 'Canmore', 'Cardston', 'Carstairs', 'Chestermere', 'Claresholm', 'Coaldale', 'Coalhurst', 'Cochrane', 'Cold Lake', 'Crossfield', 'Devon', 'Didsbury', 'Drayton Valley', 'Edmonton', 'Edson', 'Elk Point', 'Fairview', 'Falher', 'Fort Macleod', 'Fort McMurray', 'Fort Saskatchewan', 'Fox Creek', 'Gibbons', 'Grand Centre', 'Grande Cache', 'Grande Prairie', 'Grimshaw', 'Hanna', 'Heritage Pointe', 'High Level', 'High Prairie', 'High River', 'Hinton', 'Irricana', 'Jasper Park Lodge', 'Killam', 'Lac La Biche', 'Lacombe', 'Lamont', 'Larkspur', 'Laurel', 'Leduc', 'Lethbridge', 'Lloydminster', 'Magrath', 'Manning', 'Mannville', 'Maple Ridge', 'Mayerthorpe', 'Medicine Hat', 'Mill Woods Town Centre', 'Millet', 'Morinville', 'Nanton', 'Okotoks', 'Olds', 'Peace River', 'Penhold', 'Picture Butte', 'Pincher Creek', 'Ponoka', 'Provost', 'Raymond', 'Red Deer', 'Rideau Park', 'Rimbey', 'Rocky Mountain House', 'Sexsmith', 'Sherwood Park', 'Silver Berry', 'Slave Lake', 'Smoky Lake', 'Spirit River', 'Springbrook', 'Spruce Grove', 'St. Albert', 'Stettler'],
    'British Columbia': ['Prince George', 'Kelowna', 'Surrey', 'Vancouver', 'Victoria', 'Nanaimo', 'Kamloops', 'Abbotsford', 'Burnaby', 'Coquitlam', 'Delta', 'Richmond', 'New Westminster', 'North York', 'West Vancouver', 'Saanich'],
    'Manitoba': ['Winnipeg', 'Brandon', 'Portage la Prairie', 'Thompson', 'Selkirk', 'Steinbach'],
    'New Brunswick': ['Saint John', 'Fredericton', 'Moncton', 'Bathurst', 'St. Stephen', 'Campbellton'],
    'Newfoundland and Labrador': ['St. John\'s', 'Corner Brook', 'Gander', 'Grand Falls-Windsor'],
    'Northwest Territories': ['Yellowknife', 'Hay River', 'Inuvik'],
    'Nova Scotia': ['Halifax', 'Cape Breton', 'Sydney', 'Glace Bay', 'New Waterford'],
    'Nunavut': ['Iqaluit', 'Rankin Inlet'],
    'Ontario': ['Toronto', 'Ottawa', 'Hamilton', 'London', 'Windsor', 'Kitchener', 'Mississauga', 'Brampton', 'Barrie', 'Guelph', 'Thunder Bay', 'Kingston', 'Sudbury'],
    'Prince Edward Island': ['Charlottetown', 'Summerside'],
    'Quebec': ['Montreal', 'Quebec City', 'Laval', 'Gatineau', 'Longueuil', 'Sherbrooke', 'Trois-Rivieres', 'St-Jerome'],
    'Saskatchewan': ['Saskatoon', 'Regina', 'Prince Albert', 'Moose Jaw', 'Lloydminster'],
    'Yukon': ['Whitehorse', 'Dawson City']
  },

  'Egypt': {
    'Alexandria': ['Alexandria', 'Borg El Arab', 'Sidi Bishr'],
    'Aswan': ['Aswan', 'Abu Simbel', 'Edfu'],
    'Asyut': ['Asyut', 'Manfalut'],
    'Beheira': ['Damanhur', 'Kafr El-Zayyat'],
    'Beni Suef': ['Beni Suef', 'El Fashn'],
    'Cairo': ['Cairo', 'New Cairo', 'Heliopolis', 'Maadi'],
    'Dakahlia': ['Mansoura', 'Mit Ghamr', 'Aga'],
    'Damietta': ['Damietta', 'Ras El Bar', 'Port Said'],
    'Faiyum': ['Faiyum', 'Ibshaway', 'Sennuris'],
    'Gharbia': ['Tanta', 'Kafr El-Zayyat', 'Mahalla Al Kubra'],
    'Giza': ['Giza', '6th of October City', 'Helwan', 'Dahshur'],
    'Helwan': ['Helwan', 'El Obour', 'El Sherouk'],
    'Ismailia': ['Ismailia', 'Fayid', 'Abu Zaabal'],
    'Kafr El-Sheikh': ['Kafr El-Sheikh', 'Dessuq'],
    'Kalyoubia': ['Shoubra El-Khayma', 'El-Qalyoubia', 'Benha'],
    'Luxor': ['Luxor', 'Karnak'],
    'Matruh': ['Mersa Matruh', 'Siwa'],
    'Minya': ['Minya', 'Beni Hassan', 'Samalut'],
    'Monufia': ['Shibin El-Kom', 'Menouf'],
    'New Valley': ['Kharga', 'Dakhla'],
    'North Sinai': ['Arish', 'Rafah', 'Sheikh Zuwaid'],
    'Port Said': ['Port Said', 'Port Fouad'],
    'Qalyubia': ['Benha', 'Qalyub', 'Shubra El-Khayma'],
    'Qena': ['Qena', 'Dendera', 'Coptos'],
    'Red Sea': ['Hurghada', 'El Gouna', 'Marsa Alam'],
    'Sharjah': ['Sharjah'],
    'Suez': ['Suez', 'Ain Sukhna', 'Port Tawfik']
  },

  'Ghana': {
    'Ahafo Region': ['Goaso', 'Tepa', 'Mim'],
    'Ashanti Region': ['Kumasi', 'Obuasi', 'Bekwai', 'Sekyedumase'],
    'Bono East Region': ['Techiman', 'Nkoranza', 'Kintampo'],
    'Bono Region': ['Sunyani', 'Fiapre', 'Dormaa Ahenkro'],
    'Central Region': ['Cape Coast', 'Sekondi-Takoradi', 'Winneba', 'Dunkwa-on-Offin'],
    'Eastern Region': ['Koforidua', 'Akim Oda', 'Akim Tafo'],
    'Greater Accra Region': ['Accra', 'Tema', 'Ashaiman'],
    'North East Region': ['Bolgatanga', 'Bawku', 'Navrongo'],
    'Northern Region': ['Tamale', 'Yendi', 'Gushegu'],
    'Oti Region': ['Dambai', 'Krachi West'],
    'Savannah Region': ['Damongo', 'Wa'],
    'Upper East Region': ['Bolgatanga', 'Bawku', 'Navrongo', 'Zuarungu'],
    'Upper West Region': ['Wa', 'Lawra', 'Jirapa'],
    'Volta Region': ['Ho', 'Keta', 'Aflao'],
    'Western North Region': ['Sefwi Wiawso', 'Juaso'],
    'Western Region': ['Takoradi', 'Sekondi', 'Tarkwa', 'Shama']
  },

  'Jordan': {
    'Ajloun': ['Ajlun', 'Rasoun'],
    'Aqaba': ['Aqaba', 'Wadi Rum'],
    'Balqa': ['Salt', 'Fuheis', 'Amman Beach'],
    'Irbid': ['Irbid', 'Ramtha', 'Daraa'],
    'Jarash': ['Jerash', 'Sukhneh'],
    'Jerash': ['Jerash', 'Sakhnin'],
    'Karak': ['Karak', 'Mu\'tah'],
    'Ma\'an': ['Ma\'an', 'Petra', 'Wadi Rum'],
    'Madaba': ['Madaba', 'Mukawir'],
    'Mafraq': ['Mafraq', 'Al-Jafr'],
    'Zarqa': ['Zarqa', 'Russeifa'],
    'Zarka': ['Zarka', 'Jerash']
  },

  'Kenya': {
    'Baringo': ['Kabarnet', 'Marigat', 'Tiaty'],
    'Bomet': ['Bomet', 'Sotik', 'Kericho'],
    'Bungoma': ['Bungoma', 'Webuye', 'Kimilili'],
    'Busia': ['Busia', 'Nambale'],
    'Elgeyo-Marakwet': ['Iten', 'Eldoret'],
    'Embu': ['Embu', 'Runyenjes'],
    'Garissa': ['Garissa', 'Kinna'],
    'Homa Bay': ['Homa Bay', 'Oyugis'],
    'Isiolo': ['Isiolo', 'Merti'],
    'Kajiado': ['Kajiado', 'Ngong', 'Ongata Rongai'],
    'Kakamega': ['Kakamega', 'Mumias'],
    'Kamba': ['Kamba', 'Makueni'],
    'Kericho': ['Kericho', 'Kisii'],
    'Kiambu': ['Kiambu', 'Nyeri', 'Murang\'a'],
    'Kilifi': ['Kilifi', 'Mombasa', 'Malindi'],
    'Kirinyaga': ['Kerugoya', 'Kutus'],
    'Kisii': ['Kisii', 'Kericho'],
    'Kisumu': ['Kisumu', 'Nakuru'],
    'Kitui': ['Kitui', 'Wote'],
    'Kwale': ['Kwale', 'Mombasa'],
    'Laikipia': ['Nanyuki', 'Naro Moru'],
    'Lamu': ['Lamu', 'Kiunga'],
    'Machakos': ['Machakos', 'Athi River'],
    'Makueni': ['Wote', 'Mtito Andei'],
    'Mandera': ['Mandera', 'Kalacha'],
    'Mara': ['Kericho', 'Orok'],
    'Marsabit': ['Marsabit', 'Laisamis'],
    'Mombasa': ['Mombasa', 'Likoni'],
    'Muranga': ['Murang\'a', 'Kenol'],
    'Nairobi': ['Nairobi', 'Kiambu', 'Thika'],
    'Nakuru': ['Nakuru', 'Naivasha', 'Kericho'],
    'Nandi': ['Kapsabet', 'Nandi Hills'],
    'Narok': ['Narok', 'Oloolua'],
    'Nyamira': ['Nyamira', 'Kisii'],
    'Nyeri': ['Nyeri', 'Murang\'a'],
    'Samburu': ['Maralal', 'Wamba'],
    'Siaya': ['Kisumu', 'Siaya'],
    'Taita Taveta': ['Voi', 'Wundanyi'],
    'Tana River': ['Hola', 'Garsen'],
    'Tharaka Nithi': ['Chogoria', 'Meru'],
    'Trans Nzoia': ['Kitale', 'Broderick Falls'],
    'Turkana': ['Lodwar', 'Kalokol'],
    'Uasin Gishu': ['Eldoret', 'Kapchorwa'],
    'Vihiga': ['Hamisi', 'Kakamega'],
    'Wajir': ['Wajir', 'Kalacha'],
    'West Pokot': ['Kapenguria', 'Makutano']
  },

  'Kuwait': {
    'Ahmadi': ['Al Ahmadi', 'Fahaheel', 'Mangaf', 'Shuwaikh'],
    'Farwaniya': ['Al-Farwaniyah', 'Jleeb Al-Shuyoukh', 'Khaitan', 'Salmi'],
    'Hawalli': ['Hawalli', 'Salmiya', 'Jabriya', 'Salwa'],
    'Jahra': ['Jahra', 'Kabd', 'Sabriya'],
    'Mubarak Al-Kabeer': ['Mubarak Al-Kabeer', 'Sabah Al-Ahmad'],
    'Capital': ['Kuwait City', 'Dasma', 'Sharq', 'Qibla']
  },

  'Morocco': {
    'Casablanca-Settat Region': ['Casablanca', 'Mohammadia', 'El Jadida', 'Settat', 'Safi'],
    'Fès-Meknès Region': ['Fes', 'Meknes', 'Ifrane', 'Immouzzer Kandar'],
    'Marrakesh-Safi Region': ['Marrakesh', 'Safi', 'Essaouira', 'Ouirgane'],
    'Oriental Region': ['Oujda', 'Berkane', 'Jerada', 'Taourirt'],
    'Rabat-Salé-Kénitra Region': ['Rabat', 'Salé', 'Kenitra', 'Skhirat'],
    'Souss-Massa Region': ['Agadir', 'Taghazout', 'Tiznit', 'Sidi Ifni'],
    'Tangier-Tetouan-Al Hoceima Region': ['Tangier', 'Tetouan', 'Al Hoceima', 'Larache'],
    'Daraa-Tafilalet Region': ['Errachidia', 'Erfoud', 'Midelt', 'Tinerhir']
  },

  'Philippines': {
    'National Capital Region': ['Manila', 'Quezon City', 'Makati', 'Taguig', 'Caloocan', 'Valenzuela'],
    'Calabarzon': ['Laguna', 'Cavite', 'Batangas', 'Rizal', 'Quezon'],
    'Central Visayas': ['Cebu City', 'Lapu-Lapu City', 'Mandaue', 'Bohol', 'Negros Oriental'],
    'Davao Region': ['Davao City', 'Tagum', 'Panabo', 'Mati'],
    'Ilocos Region': ['Laoag', 'Vigan', 'Dagupan'],
    'Cagayan Valley': ['Tuguegarao', 'Bayombong', 'Santiago'],
    'Cordillera Administrative Region': ['Baguio', 'Benguet', 'Ifugao'],
    'Central Luzon': ['San Fernando', 'Cabanatuan', 'Nueva Ecija'],
    'Bicol Region': ['Naga', 'Legazpi', 'Daet'],
    'Mimaropa': ['Puerto Princesa', 'Calapan'],
    'Western Visayas': ['Iloilo City', 'Bacolod', 'Antique'],
    'Zamboanga Peninsula': ['Zamboanga City', 'Dipolog'],
    'Northern Mindanao': ['Cagayan de Oro', 'Butuan'],
    'Caraga': ['Butuan City', 'Surigao City'],
    'Bangsamoro': ['Cotabato City', 'General Santos']
  },

  'Qatar': {
    'Ad Dawhah': ['Doha', 'Old Doha'],
    'Al Rayyan': ['Al Rayyan', 'Abu Hamour', 'Al Gharrafa', 'Duhail'],
    'Al Wakrah': ['Al Wakrah', 'Mesaieed', 'Umm Salal'],
    'Al Khor': ['Al Khor', 'Al Thakhira', 'Al Markhiya'],
    'Ash Shahaniya': ['Ash Shahaniya', 'Al Wukair'],
    'Umm Salal': ['Umm Salal Ali', 'Umm Salal Mohammed'],
    'Ash Shammal': ['Ash Shammal', 'Fuwairit'],
    'Jariyan Al Batnah': ['Jariyan Al Batnah']
  },

  'Saudi Arabia': {
    'Riyadh': ['Riyadh', 'Al-Kharj', 'Diriyah', 'Hatat Bani Tamim'],
    'Makkah': ['Mecca', 'Jeddah', 'Taif', 'Medina'],
    'Madinah': ['Medina', 'Yanbu', 'AlUla', 'Khaybar'],
    'Eastern': ['Dammam', 'Khobar', 'Dhahran', 'Jubail', 'Qatif'],
    'Asir': ['Abha', 'Khamis Mushait'],
    'Baha': ['Baha', 'Al-Aqiq'],
    'Hail': ['Hail', 'Baqq'],
    'Jazan': ['Jazan', 'Gizan'],
    'Najran': ['Najran', 'Sharurah'],
    'Northern Borders': ['Arar', 'Sakaka'],
    'Qassim': ['Riyadh al-Qassim', 'Buraydah'],
    'Tabuk': ['Tabuk', 'Haql'],
    'Taif Region': ['Taif', 'Al-Muwassem']
  },

  'South Africa': {
    'Eastern Cape': ['Port Elizabeth', 'East London', 'Grahamstown'],
    'Free State': ['Bloemfontein', 'Welkom', 'Kroonstad'],
    'Gauteng': ['Johannesburg', 'Pretoria', 'Soweto', 'Sandton'],
    'KwaZulu-Natal': ['Durban', 'Pietermaritzburg', 'Richards Bay', 'Eshowe'],
    'Limpopo': ['Polokwane', 'Louis Trichardt', 'Musina'],
    'Mpumalanga': ['Nelspruit', 'Witbank', 'Middelburg'],
    'Northern Cape': ['Kimberley', 'Upington', 'Kuruman'],
    'North West': ['Mafikeng', 'Rustenburg', 'Brits'],
    'Western Cape': ['Cape Town', 'Stellenbosch', 'George', 'Paarl']
  },

  'Turkey': {
    'Istanbul': ['Istanbul', 'Besiktas', 'Fatih'],
    'Ankara': ['Ankara', 'Altindag', 'Cankaya'],
    'Izmir': ['Izmir', 'Alsancak', 'Bornova'],
    'Bursa': ['Bursa', 'Nilüfer', 'Osmangazi'],
    'Antalya': ['Antalya', 'Konyaalti', 'Lara'],
    'Adana': ['Adana', 'Seyhan', 'Çukurova'],
    'Gaziantep': ['Gaziantep', 'Şahinbey'],
    'Mersin': ['Mersin', 'Tarsus', 'Erdemli'],
    'Diyarbakir': ['Diyarbakır', 'Sur', 'Kayapınar'],
    'Kayseri': ['Kayseri', 'Melikgazi'],
    'Samsun': ['Samsun', 'Atakum', 'İlkadım'],
    'Konya': ['Konya', 'Meram', 'Selçuklu'],
    'Eskişehir': ['Eskişehir', 'Tepebaşı'],
    'Malatya': ['Malatya', 'Battalgazi'],
    'Kahramanmaraş': ['Kahramanmaraş', 'Dulkadiroğlu'],
    'Van': ['Van', 'İpekyolu'],
    'Rize': ['Rize', 'Çayeli'],
    'Isparta': ['Isparta', 'Merkez'],
    'Denizli': ['Denizli', 'Pamukkale'],
    'Elazığ': ['Elazığ', 'Merkez']
  },

  'United Arab Emirates': {
    'Abu Dhabi': ['Abu Dhabi City', 'Al Ain', 'Al Dhafra', 'Liwa'],
    'Dubai': ['Dubai City', 'Hatta', 'Jumeirah'],
    'Sharjah': ['Sharjah City', 'Khor Fakkan', 'Kalba', 'Ajman'],
    'Ajman': ['Ajman City', 'Manama', 'Masfoot'],
    'Ras Al Khaimah': ['Ras Al Khaimah City', 'Al Jazirah Al Hamra', 'Khatt'],
    'Fujairah': ['Fujairah City', 'Habshan'],
    'Umm Al Quwain': ['Umm Al Quwain City', 'Falaj Al Quin']
  },

  'United States': {
    'Alabama': ['Birmingham', 'Huntsville', 'Mobile', 'Montgomery', 'Tuscaloosa', 'Auburn', 'Decatur', 'Gadsden'],
    'Alaska': ['Anchorage', 'Juneau', 'Fairbanks', 'Sitka', 'Kenai'],
    'Arizona': ['Phoenix', 'Mesa', 'Chandler', 'Scottsdale', 'Glendale', 'Gilbert', 'Tucson', 'Tempe'],
    'Arkansas': ['Little Rock', 'Fort Smith', 'Fayetteville', 'Jonesboro', 'Bentonville', 'Pine Bluff'],
    'California': ['Los Angeles', 'San Diego', 'San Jose', 'San Francisco', 'Fresno', 'Sacramento', 'Oakland', 'Long Beach', 'Bakersfield', 'Anaheim'],
    'Colorado': ['Denver', 'Colorado Springs', 'Aurora', 'Fort Collins', 'Lakewood', 'Pueblo', 'Westminster'],
    'Connecticut': ['Bridgeport', 'New Haven', 'Hartford', 'Stamford', 'Waterbury', 'Norwalk'],
    'Delaware': ['Wilmington', 'Dover', 'Newark', 'Clifford', 'Middletown'],
    'Florida': ['Jacksonville', 'Miami', 'Tampa', 'Orlando', 'St. Petersburg', 'Hialeah', 'Fort Lauderdale', 'Tallahassee'],
    'Georgia': ['Atlanta', 'Augusta', 'Columbus', 'Savannah', 'Athens', 'Macon', 'Sandy Springs', 'Johns Creek'],
    'Hawaii': ['Honolulu', 'Hilo', 'Kailua', 'Kaneohe', 'Waipahu'],
    'Idaho': ['Boise', 'Nampa', 'Meridian', 'Coeur d\'Alene', 'Pocatello'],
    'Illinois': ['Chicago', 'Aurora', 'Rockford', 'Joliet', 'Naperville', 'Springfield', 'Peoria', 'Evanston'],
    'Indiana': ['Indianapolis', 'Fort Wayne', 'Evansville', 'South Bend', 'Bloomington', 'Carmel', 'Muncie'],
    'Iowa': ['Des Moines', 'Cedar Rapids', 'Davenport', 'Sioux City', 'Iowa City', 'Waterloo', 'Council Bluffs'],
    'Kansas': ['Kansas City', 'Wichita', 'Overland Park', 'Topeka', 'Olathe', 'Lawrence', 'Salina'],
    'Kentucky': ['Louisville', 'Lexington', 'Bowling Green', 'Owensboro', 'Covington', 'Hopkinsville'],
    'Louisiana': ['New Orleans', 'Baton Rouge', 'Shreveport', 'Lafayette', 'Lake Charles', 'Monroe'],
    'Maine': ['Portland', 'Lewiston', 'Bangor', 'South Portland', 'Auburn', 'Biddeford'],
    'Maryland': ['Baltimore', 'Annapolis', 'Frederick', 'Rockville', 'Gaithersburg', 'Bowie'],
    'Massachusetts': ['Boston', 'Worcester', 'Springfield', 'Lowell', 'Cambridge', 'Brockton'],
    'Michigan': ['Detroit', 'Grand Rapids', 'Warren', 'Sterling Heights', 'Ann Arbor', 'Lansing', 'Flint'],
    'Minnesota': ['Minneapolis', 'St. Paul', 'Rochester', 'Duluth', 'Saint Cloud', 'Mankato'],
    'Mississippi': ['Jackson', 'Gulfport', 'Biloxi', 'Hattiesburg', 'Meridian', 'Tupelo'],
    'Missouri': ['Kansas City', 'St. Louis', 'Springfield', 'Columbia', 'St. Joseph', 'Independence'],
    'Montana': ['Billings', 'Missoula', 'Great Falls', 'Bozeman', 'Helena', 'Butte'],
    'Nebraska': ['Omaha', 'Lincoln', 'Bellevue', 'Grand Island', 'Kearney', 'Norfolk'],
    'Nevada': ['Las Vegas', 'Henderson', 'Reno', 'North Las Vegas', 'Sparks', 'Carson City'],
    'New Hampshire': ['Manchester', 'Nashua', 'Concord', 'Portsmouth', 'Rochester', 'Dover'],
    'New Jersey': ['Newark', 'Jersey City', 'Paterson', 'Elizabeth', 'Trenton', 'Clifton'],
    'New Mexico': ['Albuquerque', 'Santa Fe', 'Las Cruces', 'Rio Rancho', 'Clovis', 'Farmington'],
    'New York': ['Binghamton', 'Buffalo', 'Catskills', 'Chautauqua', 'Elmira / Corning', 'Finger Lakes', 'Glens Falls', 'Hudson Valley', 'Ithaca', 'Long Island', 'New York City', 'Oneonta', 'Plattsburgh / Adirondacks', 'Rochester', 'Syracuse', 'Utica / Rome', 'Watertown'],
    'North Carolina': ['Charlotte', 'Raleigh', 'Greensboro', 'Durham', 'Winston-Salem', 'Fayetteville', 'Wilmington'],
    'North Dakota': ['Bismarck', 'Fargo', 'Grand Forks', 'Minot', 'Williston', 'Mandan'],
    'Ohio': ['Columbus', 'Cleveland', 'Cincinnati', 'Toledo', 'Akron', 'Dayton', 'Parma'],
    'Oklahoma': ['Oklahoma City', 'Tulsa', 'Norman', 'Broken Arrow', 'Edmond', 'Lawton'],
    'Oregon': ['Portland', 'Eugene', 'Salem', 'Gresham', 'Hillsboro', 'Bend'],
    'Pennsylvania': ['Philadelphia', 'Pittsburgh', 'Allentown', 'Erie', 'Reading', 'Scranton', 'Bethlehem'],
    'Rhode Island': ['Providence', 'Warwick', 'Cranston', 'Pawtucket', 'East Providence'],
    'South Carolina': ['Charleston', 'Columbia', 'Greenville', 'Summerville', 'Myrtle Beach', 'Spartanburg'],
    'South Dakota': ['Sioux Falls', 'Rapid City', 'Aberdeen', 'Brookings', 'Watertown', 'Mitchell'],
    'Tennessee': ['Memphis', 'Nashville', 'Knoxville', 'Chattanooga', 'Clarksville', 'Jackson'],
    'Texas': ['Houston', 'San Antonio', 'Dallas', 'Austin', 'Fort Worth', 'El Paso', 'Arlington', 'Corpus Christi', 'Plano', 'Laredo'],
    'Utah': ['Salt Lake City', 'Provo', 'Ogden', 'Orem', 'West Valley City', 'Sandy', 'Lehi'],
    'Vermont': ['Burlington', 'Rutland', 'Montpelier', 'Barre', 'Bennington'],
    'Virginia': ['Virginia Beach', 'Richmond', 'Arlington', 'Alexandria', 'Hampton', 'Roanoke', 'Charlottesville'],
    'Washington': ['Seattle', 'Spokane', 'Tacoma', 'Vancouver', 'Bellevue', 'Kent', 'Everett'],
    'West Virginia': ['Charleston', 'Huntington', 'Parkersburg', 'Morgantown', 'Wheeling'],
    'Wisconsin': ['Milwaukee', 'Madison', 'Green Bay', 'Kenosha', 'Racine', 'Appleton'],
    'Wyoming': ['Cheyenne', 'Casper', 'Laramie', 'Gillette', 'Rock Springs', 'Sheridan']
  }
};
